encrypta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from encrypta import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(url='/vault/', permanent=False)),
    path("vault/", include("vault.urls", namespace="vault")),
    path("user/", include("users.urls", namespace="users")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("settings/", views.settings, name="settings"),
    path("logout/", views.logout, name="logout"),
    path("delete-user/", views.delete, name="delete"),
    path("api/", include("users.api.urls", namespace="users-api")),
]

vault/api/urls.py
from django.urls import include, path
from . import views

from rest_framework import routers

app_name = "api"

router = routers.DefaultRouter()
router.register(r'records', views.RecordsViewSet)
router.register(r'categories', views.CategoriesViewSet)


urlpatterns = [
    path('', include(router.urls))
]

vault/urls.py
from django.urls import include, path

from vault import views

app_name = "vault"

urlpatterns = [
    path("", views.vault, name="vault"),
    path("save-record/", views.save_record, name="save"),
    path("change-record/", views.get_record_form, name="change"),
    path("delete-record/", views.delete_record, name="delete"),
    path("new-category/", views.new_category, name="new-category"),
    path("api/", include("vault.api.urls", namespace="vault-api")),
]

vault/models.py
from unicodedata import category
from django.db import models

from users.models import User
from vault.utils import decrypt, encrypt

from .validators import latin_alphabet_regex

class Categories(models.Model):
    name = models.CharField(
        unique=True, max_length=150, verbose_name="Название категории"
    )
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"
        ordering = ("name",)

    def __str__(self):
        return f"{self.name} | {self.user.username}"


class Records(models.Model):
    # app_name = models.CharField(max_length=150, verbose_name="Название приложения")
    app_name = models.CharField(max_length=150, verbose_name="Название приложения")
    username = models.CharField(
        max_length=150, null=True, blank=True, verbose_name="Имя пользователя"
    )
    password = models.CharField(
        max_length=300, null=True, blank=True, verbose_name="Пароль"
    )
    favicon = models.ImageField(
        upload_to="favicon_images",
        blank=True,
        null=True,
        verbose_name="Иконка приложения",
    )
    url = models.CharField(max_length=500, blank=True, null=True, verbose_name="Адрес")
    category = models.ForeignKey(
        to=Categories,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Категория",
    )
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )
    creation_date = models.DateTimeField(
        auto_now_add=True, null=True, verbose_name="Дата создания"
    )
    lastmodified_date = models.DateTimeField(
        auto_now=True, null=True, verbose_name="Дата последнего изменения"
    )
    totp_secret = models.CharField(
        max_length=32,
        null=True,
        blank=True,
        unique=True,
        verbose_name="2FA секретный ключ",
        validators=[latin_alphabet_regex],
    )

    class Meta:
        db_table = "record"
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return f'{self.user.username} | {self.category.name if self.category else "Без категории"} | {self.app_name}'

    def encrypt_data(self, key):
        self.app_name = encrypt(self.app_name, key)
        self.username = encrypt(self.username, key)
        self.password = encrypt(self.password, key)
        self.url = encrypt(self.url, key)

    def decrypt_data(self, key):
        self.app_name = decrypt(self.app_name, key).decode("utf-8")
        self.username = decrypt(self.username, key).decode("utf-8")
        self.password = decrypt(self.password, key).decode("utf-8")
        self.url = decrypt(self.url, key).decode("utf-8")

vault/forms.py
from django import forms


from vault.models import Records, Categories


class NewRecordForm(forms.ModelForm):
    class Meta:
        model = Records
        fields = (
            "app_name",
            "username",
            "password",
            "url",
        )

    app_name = forms.CharField()
    username = forms.CharField(required=False)
    password = forms.CharField(required=False)
    url = forms.CharField(required=False)
    


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = ("name",)

    name = forms.CharField()

    def clean_name(self):
        data= self.cleaned_data["name"]
        if Categories.objects.filter(name=data).exists():
            raise forms.ValidationError("Такая категория уже существует", code="unique")
        
        return data

vault/api/views.py
import jwt
from encrypta.settings import SECRET_KEY
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.response import Response

from vault.api.serializers import CategoriesSerializer, RecordsSerializer
from vault.models import Categories, Records


class RecordsViewSet(ModelViewSet):
    queryset = Records.objects.all()
    serializer_class = RecordsSerializer

    def get_queryset(self):
        try:
            token = self.request.headers["Authorization"].split(" ")[1]
            decoded_token = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
            user_id = decoded_token["user_id"]
            user_queryset = Records.objects.filter(user_id=user_id).order_by('app_name')
            return user_queryset
        except:
            # return Response({"error": "Недействительный токен"})
            return Records.objects.none()

    @action(methods=["get"], detail=False)
    def categories(self, request):
        try:
            token = self.request.headers["Authorization"].split()[1]
            payload = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
            user_id = payload["user_id"]
        except jwt.exceptions.DecodeError:
            return Response({"error": "Недействительный токен"})
        cats = Categories.objects.filter(user_id=user_id)
        return Response({"cats": [c.name for c in cats]})


class CategoriesViewSet(ModelViewSet):
    queryset = Categories.objects.all()
    serializer_class = CategoriesSerializer

    def get_queryset(self):
        try:
            token = self.request.headers["Authorization"].split(" ")[1]
            decoded_token = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
            user_id = decoded_token["user_id"]
            return Categories.objects.filter(user_id=user_id)
        except:
            return Response({"error": "Недействительный токен"})

vault/views.py
from django.core.cache import cache
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse
from vault.forms import NewCategoryForm, NewRecordForm
from django.contrib.auth.decorators import login_required

from vault.models import Categories, Records

@login_required
def vault(request):
    """
    Возвращает все записи текущего пользователя
    """
    master_encryption_key = request.session.get("master-encryption-key", None)
    records = Records.objects.filter(user=request.user)
    if master_encryption_key:
        master_encryption_key = master_encryption_key.encode("utf-8")
        for record in records:
            record.decrypt_data(master_encryption_key)

    context = {
        "title": "Главная",
        "records": records,
    }
    return render(request, "vault/vault.html", context)


@login_required
def save_record(request):
    """
    Сохраняет запись в базе данных
    """
    if request.method == "POST":
        record_id = request.POST.get("id", None)
        if record_id:
            record = get_object_or_404(Records, user=request.user, id=record_id)
            form = NewRecordForm(request.POST, instance=record)
        else:
            form = NewRecordForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            if request.POST.get("category"):
                post.category = get_object_or_404(
                    Categories, user=request.user, name=request.POST["category"]
                )
            encryption_key = request.session.get("master-encryption-key")
            encryption_key = encryption_key.encode("utf-8")
            post.encrypt_data(encryption_key)
            post.save()
            return HttpResponseRedirect(reverse("vault:vault"))
    return HttpResponseRedirect(reverse("vault:vault"))


@login_required
def get_record_form(request):
    """
    Получает данные выбранной записи по id и отправляет их по AJAX
    """
    record_id = request.POST.get("record_id")
    record = Records.objects.get(id=record_id)

    encryption_key = request.session.get("master-encryption-key")
    encryption_key = encryption_key.encode("utf-8")
    record.decrypt_data(encryption_key)

    change_form_html = render_to_string(
        "vault/edit-record-form.html", {"record": record}, request=request
    )

    response_data = {
        "change_form_html": change_form_html,
    }

    return JsonResponse(response_data)


@login_required
def delete_record(request):
    """
    Удаляет запись по id
    """
    if request.method == "POST":
        record = Records.objects.filter(user=request.user).get(
            id=request.POST.get("id")
        )
        record.delete()
    return HttpResponseRedirect(reverse("vault:vault"))


@login_required
def new_category(request):
    """
    Создает новую категорию
    """
    if request.method == "POST":
        form = NewCategoryForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            cache_key = f"category_list_{request.user.id}"
            cache.delete(cache_key)
        else:
            # TODO Здесь необходимо вернуть перерисованную форму с сообщением об ошибке
            ...

    else:
        form = NewCategoryForm()

    return HttpResponseRedirect(reverse("vault:vault"))

templates/vault/change-record.html
{% load static %}
{% load password_tags %}

<div onclick="closeDialog('modal-change-record')" id="modal-change-record" class="fixed left-0 top-0 bg-black bg-opacity-10 w-screen h-screen justify-center items-center opacity-0 hidden transition-opacity duration-300">
    <!-- Содержание модального окна -->
    <div onclick="event.stopImmediatePropagation()" class="bg-white rounded shadow-md p-1 w-[40rem] flex-col flex-none">
        <!-- Заголовок модального окна -->
        <div class="w-full flex flex-start justify-between px-7 py-4 border-b-2 border-gray-300">
            <h1 class="text-lg">Редактирование</h1>
            <button onclick="closeDialog('modal-change-record')">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                  </svg>                          
            </button>
        </div>
        <!-- Тело модального окна -->
        <div id="edit-record-form">
            {% include "vault/edit-record-form.html" %}
        </div>
    </div>
</div>

templates/vault/edit-record-form.html
{% load static %}
{% load password_tags %}
<form action="{% url "vault:save" %}" method="post">
    <div class="flex flex-col px-7 py-4 h-[30 rem]">
        {% csrf_token %}     
        <!-- 1 Ряд -->
        <input type="hidden" value="{{record.id}}" name="id"></input> 
        <div class="flex justify-between">
            <div class="p-2 mb-[1rem]">
                <label for="id_app_name">Название приложения</label>
                <input type="text" id="id_app_name" name="app_name" value="{{record.app_name}}" required 
                class="form-field"></input>
            </div>
            <div class="p-2 mb-[1rem]">
                <label for="id_category">Категория</label>
                <select id="id_category" name="category" class="form-field">
                {% get_category_list_for_current_user user=user as Categories %}
                {% for category in Categories %}
                    <option 
                        {% if category.name == record.category.name %}
                            selected
                        {% endif %} 
                        value={{category.name}}
                    >
                        {{category.name}}
                    </option>
               {% endfor %}
                </select>
            </div>
        </div>
        <!-- 2 Ряд -->
        <div class="flex justify-between">
            <div class="p-2 mb-[1rem]">
                <label for="id_username">Имя пользователя</label>
                <input type="text" id="id_username" name="username" value="{{record.username}}"  
                class="form-field"></input>
            </div>
            <div class="p-2 mb-[1rem]">
                <label for="id_password">Пароль</label>
                <input type="password" id="id_password" name="password" value="{{record.password}}"  
                class="form-field"></input>
            </div>
        </div>
        <!-- 3 Ряд -->
        <div class="flex justify-between">
            <div class="p-2 mb-[1rem]">
                <label for="id_url">URL-адрес</label>
                <input type="text" id="id_url" name="url" value="{{record.url}}" 
                class="form-field"></input>
            </div>
        </div>
    </div>
    <!-- Футер модального окна -->
    <div class="w-full flex flex-start justify-between px-7 py-4 border-t-2 border-gray-300">
        <button type="submit" class="px-2 py-1 border-2 bg-slate-500 border-transparent rounded-md hover:bg-slate-600">
            <span class="font-medium text-white">Сохранить</span>
        </button>
</form>
    {% if record.id %}
        <form action="{% url "vault:delete" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{record.id}}" name="id"></input> 
            <button type="submit" class="flex px-1 items-center justify-center border-[3px] rounded-md border-red-400">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>              
            </button>
        </form>
    {% endif %}
    </div>

templates/vault/new-category-form.html
<form action="{% url "vault:new-category" %}" method="POST">
    {% csrf_token %}
    <div class="flex flex-col px-7">
        <div class="py-2">
            <label for="id_category_name">Название категории</label>
            <input type="text" id="id_category_name" name="name" required 
            class="form-field"></input>
        </div>
        <div class="mb-[1rem] text-pink-500 error-message">
            <!--Здесь необходимо вставить сообщение об ошибке униальности-->
            {{error_message}}
        </div>
    </div>
    <div class="w-full flex flex-start justify-between px-7 py-4 border-t-2 border-gray-300">
        <button type="submit" class="px-2 py-1 border-2 bg-slate-500 border-transparent rounded-md hover:bg-slate-600">
            <span class="font-medium text-white">Сохранить</span>
        </button>
    </div>
</form>

templates/vault/new-category.html
{% load static %}
{% load password_tags %}

<div onclick="closeDialog('modal-new-category')" id="modal-new-category" class="fixed left-0 top-0 bg-black bg-opacity-10 w-screen h-screen justify-center items-center opacity-0 hidden transition-opacity duration-300">
    <!-- Содержание модального окна -->
    <div onclick="event.stopImmediatePropagation()" class="bg-white rounded shadow-md p-1 w-[24rem] flex-col flex-none">
        <!-- Заголовок модального окна -->
        <div class="w-full flex flex-start justify-between px-7 py-4 border-b-2 border-gray-300">
            <h1 class="text-lg">Новая категория</h1>
            <button onclick="closeDialog('modal-new-category')">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                  </svg>                          
            </button>
        </div>
        <div id="new-category-form">
            {% include "vault/new-category-form.html" %}
        </div>
    </div>
</div>

templates/vault/new-record.html
{% load static %}
{% load password_tags %}

<div onclick="closeDialog('modal-new-record')" id="modal-new-record" class="fixed left-0 top-0 bg-black bg-opacity-10 w-screen h-screen justify-center items-center opacity-0 hidden transition-opacity duration-300">
    <!-- Содержание модального окна -->
    <div onclick="event.stopImmediatePropagation()" class="bg-white rounded shadow-md p-1 w-[40rem] flex-col flex-none">
        <!-- Заголовок модального окна -->
        <div class="w-full flex flex-start justify-between px-7 py-4 border-b-2 border-gray-300">
            <h1 class="text-lg">Новый элемент</h1>
            <button onclick="closeDialog('modal-new-record')">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                  </svg>                          
            </button>
        </div>
        {% include "vault/edit-record-form.html" %}
    </div>
</div>

templates/vault/vault.html
{% extends "base.html" %}
{% load password_tags %}
{% load static %}

{% block navigation %}
{% include "includes/navbar.html" %}
{% endblock navigation %}

{% block content %}
<div class="mt-1 container flex justify-center">
    <div class="flex flex-col gap-1 w-1/2">
        {% for record in records%}
        <div class="flex gap-3 h-16 justify-start align-middle bg-gray-100 hover:bg-gray-200 border-solid border-2 border-slate-300 rounded-md">        
            
            <!-- Иконка приложения -->

            {% if record.favicon %}
                <img class="my-auto ml-2" src="{{record.favicon.url}}" width="32" "height=32" alt=""></img>
            {% else %}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="dimgray" class="w-[32px] h-[32px] my-auto ml-2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m20.893 13.393-1.135-1.135a2.252 2.252 0 0 1-.421-.585l-1.08-2.16a.414.414 0 0 0-.663-.107.827.827 0 0 1-.812.21l-1.273-.363a.89.89 0 0 0-.738 1.595l.587.39c.59.395.674 1.23.172 1.732l-.2.2c-.212.212-.33.498-.33.796v.41c0 .409-.11.809-.32 1.158l-1.315 2.191a2.11 2.11 0 0 1-1.81 1.025 1.055 1.055 0 0 1-1.055-1.055v-1.172c0-.92-.56-1.747-1.414-2.089l-.655-.261a2.25 2.25 0 0 1-1.383-2.46l.007-.042a2.25 2.25 0 0 1 .29-.787l.09-.15a2.25 2.25 0 0 1 2.37-1.048l1.178.236a1.125 1.125 0 0 0 1.302-.795l.208-.73a1.125 1.125 0 0 0-.578-1.315l-.665-.332-.091.091a2.25 2.25 0 0 1-1.591.659h-.18c-.249 0-.487.1-.662.274a.931.931 0 0 1-1.458-1.137l1.411-2.353a2.25 2.25 0 0 0 .286-.76m11.928 9.869A9 9 0 0 0 8.965 3.525m11.928 9.868A9 9 0 1 1 8.965 3.525" />
                </svg>              
            {% endif %}

            <!--Название приложения -->

            <div class="my-auto font-medium">
                <a href="{% url "vault:change" %}" class="change-record" data-record-id="{{record.id}}" onclick="showDialog(event, 'modal-change-record')">
                    {% csrf_token %}
                    {{record.app_name}}
                </a>
            </div>

            <!-- Поле с паролем -->

            {% get_password_for_record id=record.id user=request.user as password_value%}
            {% if password_value %}
                <div class="my-auto">
                    <input placeholder="" :type="show ? 'password' : 'text'" class="w-32 peer rounded-[7px] !border !border-gray-300 border-t-transparent 
                    bg-transparent bg-white 
                    text-gray-700 
                    outline outline-0 ring-4 ring-transparent transition-all 
                    focus:border-2 focus:!border-blue-100" type="password" readonly value="{{password_value}}">
                </div>
            {% endif %}

            <!-- Кнопка скрытия пароля -->
            
            {% if password_value %}
                <div class="my-auto w-[2rem] h-[2rem] hover:bg-gray-300 hover:border-2 hover:border-gray-400 flex justify-center items-center">
                    <button>
                        {% comment %} <img src="{% static "deps/icons/eye-detected.svg" %}"></img> {% endcomment %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        </svg>
                        
                    </button>
                </div>
            {% endif %}

             <!-- Кнопка копирования пароля -->

            {% if password_value %}
                <div class="my-auto w-[1.5rem] h-[1.5rem]">
                    <button>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
                        </svg>
                    </button>
                </div>
            {% endif %}

             <!-- Кнопка перехода -->
             
            {% if record.url %}
                <div class="my-auto w-[1.5rem] h-[1.5rem]">
                    <a href="https://{{record.url}}" target="_blank">
                        {% comment %} <img src="{% static "deps/icons/arrow-shape-turn-right-svgrepo-com.svg" %}"></img> {% endcomment %}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round"showDialog d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                        </svg>                 
                    </a>
                </div>
            {% endif %}

        </div>	
        {% endfor %}

        <!-- Кнока добавить - вызывает модальное окно -->

        <div class="w-[14rem] relative mx-auto">
            <button onclick="toggleMenu()" class="inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" id="menu-button" aria-expanded="true" aria-haspopup="true">
                Добавить
                <svg class="-mr-1 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                  </svg>
            </button>
            <div id="menu" class="hidden mt-2 w-full origin-top rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="block py-1">
                  <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                  <button onclick="showDialog(event, 'modal-new-record')" class="w-full text-gray-700 inline-block px-4 py-2 text-sm hover:bg-gray-50">Запись</button>
                  <button onclick="showDialog(event, 'modal-new-category')" class="w-full text-gray-700 inline-block px-4 py-2 text-sm hover:bg-gray-50">Категорию</button>
                </div>
            </div>
        </div>

        <!-- Модальное окно создания записи -->

        {% include "vault/new-record.html" %}
        {% include "vault/new-category.html" %}
        {% include "vault/change-record.html" %}

        </div>

            

    </div>
</div>
<script>
    function showDialog(event, modal_window){
        {% comment %} event.preventDefault(); {% endcomment %}
        let dialog = document.getElementById(modal_window);
        dialog.classList.remove("hidden");
        dialog.classList.add("flex");
        setTimeout(()=>{
            dialog.classList.add("opacity-100");
        }, 200)
        
    }

    function closeDialog(modal_window){
        let dialog = document.getElementById(modal_window);       
        dialog.classList.add("opacity-0");   
        dialog.classList.remove("opacity-100");   
        setTimeout(()=>{
            dialog.classList.add("hidden");
            dialog.classList.remove("flex");
        }, 300)
    }

    function toggleMenu() {
        const buttons = document.getElementById('menu');
        buttons.classList.toggle('hidden');
        buttons.classList.toggle('block');
    }


</script>
{% endblock content %}