encrypta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from encrypta import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(url='/vault/', permanent=False)),
    path("vault/", include("vault.urls", namespace="vault")),
    path("user/", include("users.urls", namespace="users")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("settings/", views.settings, name="settings"),
    path("logout/", views.logout, name="logout"),
    path("delete-user/", views.delete, name="delete"),
    path("api/", include("users.api.urls", namespace="users-api")),
]

vault/urls.py
from django.urls import include, path

from vault import views

app_name = "vault"

urlpatterns = [
    path("", views.vault, name="vault"),
    path("save-record/", views.save_record, name="save"),
    path("change-record/", views.get_record_form, name="change"),
    path("delete-record/", views.delete_record, name="delete"),
    path("new-category/", views.new_category, name="new-category"),
    path("api/", include("vault.api.urls", namespace="vault-api")),
]

templates/includes/navbar.html
<div class="container bg-slate-500">
    <nav class="px-0 py-2 flex flex-nowrap  ">
        <div class="pl-2 m-auto flex grow align-middle ">
            <div class="flex flex-grow justify-center align-middle">
                <ul class="pl-0 ml-0 flex flex-row gap-5">
                    <li><a href="{% url "vault:vault" %}" class="font-medium text-slate-50 hover:text-slate-200">Хранилище</a></li>
                    <li><a href="#" class="font-medium text-slate-50 hover:text-slate-200">Инструменты</a></li>
                    <li><a href="#" class="font-medium text-slate-50 hover:text-slate-200">Заметки</a></li>
                    <li><a href="{% url "users:settings" %}" class="font-medium text-slate-50 hover:text-slate-200">Настройки</a></li>
                    <li><a href="#" class="font-medium text-slate-50 hover:text-slate-200">Справка</a></li>
                    <li><a href="{% url "users:logout" %}" class="font-medium text-slate-50 hover:text-slate-200">Выход</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>