encrypta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

from encrypta import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', RedirectView.as_view(url='/vault/', permanent=False)),
    path("vault/", include("vault.urls", namespace="vault")),
    path("user/", include("users.urls", namespace="users")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from users.api.views import (
    CustomTokenObtainPairView,
    RegistrationAPIView,
    TotpSetupView,
    # TotpVerifyView,
    logout,
)


app_name = "users-api"

urlpatterns = [
    path("register/", RegistrationAPIView.as_view(), name="registration"),
    path("login/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("totp/setup/", TotpSetupView.as_view(), name="totp_setup"),
    # path("totp/verify/", TotpVerifyView.as_view(), name="verify_totp"),
    path("logout/", logout, name="logout"),
]

users/urls.py
from django.urls import include, path

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("settings/", views.settings, name="settings"),
    path("logout/", views.logout, name="logout"),
    path("delete-user/", views.delete, name="delete"),
    path("api/", include("users.api.urls", namespace="users-api")),
]

users/models.py
from encrypta import settings
import jwt
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        if not email:
            raise ValueError('The Email field must be set')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    username = models.CharField(unique=True, max_length=255, verbose_name="Имя пользователя")
    email = models.CharField(max_length=250, verbose_name="Электронная почта")
    is_active = models.BooleanField(default=True, verbose_name="Активный")
    is_staff = models.BooleanField(default=False, verbose_name="Персонал")
    date_joined = models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата регистрации")
    last_login = models.DateTimeField(auto_now=True, null=True, verbose_name="Дата последнего входа")
    totp_enabled = models.BooleanField(default=False, verbose_name="2FA")
    totp_secret = models.CharField(max_length=32, null=True, blank=True, unique=True, verbose_name="2FA секретный ключ")

    objects = UserManager()

    class Meta:
        indexes = [models.Index(fields=['username'])]
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username
    
    def get_full_name(self):
        return self.username
    
    def get_short_name(self):
        return self.username



class UserSettings(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )
    preferred_hash_algorithm = models.CharField(max_length=50, verbose_name="Алгоритм хеширования")
    totp_enabled = models.BooleanField(default=False, verbose_name="2FA")

    class Meta:
        db_table = "settings"
        verbose_name = "Настройки пользователей"
        verbose_name_plural= "Настройки пользователей"

    def __str__(self):
        return f"{self.user} | {self.preferred_hash_algorithm}"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.hashers import make_password

from django.contrib.auth.password_validation import validate_password
from django.core.validators import validate_email

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ["username", "password"]


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1"]

    username = forms.CharField()
    email = forms.CharField()
    password = forms.CharField()

    def clean_username(self):
        return self.cleaned_data["username"]

    def clean_email(self):
        return self.cleaned_data["email"]

    def clean_password1(self):
        return self.cleaned_data["password1"]

    def clean(self):
        cleaned_data = super().clean()
        self.errors.clear()
        return cleaned_data
    

    # def clean_username(self):
    #     username = self.cleaned_data["username"]
    #     if User.objects.filter(username__iexact=username).exists():
    #         raise forms.ValidationError(
    #             "Пользователь с таким именем уже существует", code="unique"
    #         )
    #     return username

    # def clean_email(self):
    #     email = self.cleaned_data["email"]
    #     try:
    #         validate_email(email)
    #     except:
    #         raise forms.ValidationError("Неправильный email", code="invalid")
    #     if User.objects.filter(email=email).exists():
    #         raise forms.ValidationError(
    #             "Пользователь с таким email уже существует", code="unique"
    #         )
    #     return email

    # def clean_password1(self):
    #     password1 = self.cleaned_data["password1"]
    #     try:
    #         validate_password(password1)
    #     except forms.ValidationError as error:
    #         raise forms.ValidationError(error.messages)
    #     return password1

    # def clean_password2(self):
    #     password1 = self.cleaned_data.get("password1")
    #     password2 = self.cleaned_data.get("password2")
    #     if password1 and password2 and password1 != password2:
    #         raise forms.ValidationError("Пароли не совпадают")
    #     return password2




class UserSettingsForm(forms.Form):
    username = forms.CharField()
    email = forms.CharField()
    hash_algorithm = forms.ChoiceField(
        choices=[
            ("pbkdf2_sha256", "pbkdf2"),
            ("argon2", "argon"),
        ]
    )

users/api/views.py
import base64
import hashlib

import pyotp

from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.views import APIView


from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.authentication import JWTAuthentication

from users.api.utils import generate_secret_key, verify_totp_code
from users.api.serializers import RegistrationSerializer
from users.models import User


class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["username"] = user.username
        # ...

        return token


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            user = serializer.user
            if user.totp_enabled:
                totp_code = request.data.get("totp_code", None)
                if totp_code and verify_totp_code(totp_code, user.totp_secret):
                    token = serializer.get_token(user)
                    return Response(
                        {"access": str(token.access_token), "refresh": str(token)},
                        status=status.HTTP_200_OK,
                    )
                else:
                    return Response(
                        {"message": "Введите TOTP код"},
                        status=status.HTTP_401_UNAUTHORIZED,
                    )
            else:
                token = serializer.get_token(user)
                return Response(
                    {"access": str(token.access_token), "refresh": str(token)},
                    status=status.HTTP_200_OK,
                )
        else:
            return Response(serializer.errors, status=status.HTTP_401_UNAUTHORIZED)


class RegistrationAPIView(APIView):
    permission_classes = (AllowAny,)
    serializer_class = RegistrationSerializer

    def post(self, request):
        user = request.data

        # Паттерн создания сериализатора, валидации и сохранения - довольно
        # стандартный, и его можно часто увидеть в реальных проектах.
        serializer = self.serializer_class(data=user)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(["POST"])
def logout(request):
    try:
        refresh_token = request.data["refresh_token"]
        token = RefreshToken(refresh_token)
        token.blacklist()
        return Response(status=status.HTTP_205_RESET_CONTENT)
    except Exception as e:
        return Response(status=status.HTTP_400_BAD_REQUEST)


class TotpSetupView(APIView):
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request):
        user = request.user

        if not user.totp_enabled:
            secret_key = generate_secret_key()
            user.totp_enabled = True
            user.totp_secret = secret_key
            user.save()
            return Response(
                {
                    "status": "success",
                    "message": "TOTP верификация успешно установлена.",
                }
            )
        else:
            return Response(
                {"status": "error", "message": "TOTP верификация уже установлена."}
            )


# class TotpVerifyView(APIView):
#     permission_classes = (AllowAny,)

#     def post(self, request):
#         totp_code = request.data.get("totp_code")
#         username = request.data.get("username")

#         try:
#             user = User.objects.get(username=username)
#         except User.DoesNotExist:
#             return Response(
#                 {"error": "Некорректный логин"}, status=status.HTTP_404_NOT_FOUND
#             )

#         if not user.totp_enabled:
#             return Response(
#                 {"error": "TOTP верификация не установлена"},
#                 status=status.HTTP_400_BAD_REQUEST,
#             )

#         if verify_totp_code(totp_code, user.totp_secret):
#             serializer = MyTokenObtainPairSerializer()
#             token = serializer.get_token(user)
#             return Response(
#                 {"access_token": str(token.access_token), "refresh_token": str(token)}
#             )
#         else:
#             return Response(
#                 {"error": "Неправильный TOTP код"}, status=status.HTTP_400_BAD_REQUEST
#             )

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db import transaction
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.hashers import make_password

from users.forms import UserLoginForm, UserRegistrationForm, UserSettingsForm
from users.models import User, UserSettings
from users.utils import get_or_create_user_settings, check_password



def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            #TODO сделать проверки для тестирования
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = None
            if user:
                settings = get_or_create_user_settings(user)

                correct_password, must_update = check_password(
                    password=password,
                    encoded=user.password,
                    hasher=settings.preferred_hash_algorithm,
                )
                if must_update:
                    user.password = make_password(password=password, salt=user.email, hasher=settings.preferred_hash_algorithm)
                    user.save()

                if correct_password:
                    hashed_password = user.password.split("$")[-1]
                    request.session["master-encryption-key"] = hashed_password
                    auth.login(request, user)
                    if request.POST.get("next", None):
                        return HttpResponseRedirect(request.POST.get("next"))
                    return HttpResponseRedirect(reverse("vault:vault"))
    else:
        form = UserLoginForm()

    context = {
        "title": "Авторизация",
        "form": form,
    }
    return render(request, "users/login.html", context)

#TODO сделать сохранение ключа в сессии при регистрации
def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            get_or_create_user_settings(user)
            auth.login(request, user)
            messages.success(request, f"{user.username}, Вы успешно зарегистрировались")
            return HttpResponseRedirect(reverse("vault:vault"))
    else:
        form = UserRegistrationForm()
    context = {
        "title": "Регистрация",
        "form": form,
    }
    return render(request, "users/registration.html", context)


@login_required
def settings(request):
    if request.method == "POST":
        form = UserSettingsForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    user.username = form.cleaned_data["username"]
                    user.email = form.cleaned_data["email"]
                    user.save()
                    settings = get_or_create_user_settings(user=user)
                    settings.preferred_hash_algorithm = form.cleaned_data[
                        "hash_algorithm"
                    ]
                    settings.save()
            except ValidationError:
                return redirect("user:settings")

    else:
        settings = get_or_create_user_settings(user=request.user)
        form = UserSettingsForm(
            initial={
                "username": request.user.username,
                "email": request.user.email,
                "settings": settings,
            }
        )

    context = {
        "title": "Профиль",
        "form": form,
    }
    return render(request, "users/settings.html", context)


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse("vault:vault"))


@login_required
def delete(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    return HttpResponseRedirect(reverse("vault:vault"))

templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% comment %} <script type="module" src="{% static "/deps/js/login.js" %}"></script> {% endcomment %}
<div class="fixed w-screen h-screen bg-slate bg-opacity-10">
    <form action="{% url "users:login" %}" id="login-form" method="post" class="mx-auto max-w-[1024px] w-full container">
        {% csrf_token %}
        <div class="p-[2rem] mt-5 mx-auto flex flex-col justify-center items-center max-w-[32rem]">
            <div class="p-[1.5rem] bg-white border-gray-200 border-1 rounded-md">
                <div class="font-medium mb-3 text-3xl flex justify-center">
                    {{title}}
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_username">
                        Имя пользователя
                    </label>
                    <input id="id_username" name="username" class="form-field" type="text" required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.username.errors %}{{form.username.errors}}{% endif %}
                    </div>
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_password">
                        Пароль
                    </label>
                    <input id="id_password" name="password" class="form-field" type="password" required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.password.errors %}{{form.password.errors}}{% endif %}
                    </div>
                </div>
                <div class="mb-8 block">
                    <a href="{% url "users:registration" %}" class="text-sky-400 hover:text-sky-500 hover:underline">
                        Регистрация
                    </a>
                </div>
                <button type="submit" class="px-2 py-1 w-full border-2 bg-slate-500 border-transparent rounded-md hover:bg-slate-600">
                    <span class="font-medium text-white">Войти</span>
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/users/profile.html
<form action="{% url "users:settings" %}" method="post" class="mx-auto max-w-[1024px] w-full container">
    {% csrf_token %}
    <div class="p-[2rem] mt-5 mx-auto flex flex-col justify-center items-center max-w-[32rem]">
        <div class="p-[1.5rem] bg-white border-gray-200 border-1 rounded-md">
            <div class="font-medium mb-3 text-3xl flex justify-center">
                {{title}}
            </div>
            <div class="mb-3 block ">
                <label class="font-normal" for="id_username">
                    Имя пользователя
                </label>
                <input id="id_username" name="username" class="form-field" type="text"
                {% if form.username.value %} value={{form.username.value}} {% endif %}
                required>
                </input>
                <div class="pt-1 block text-pink-500">
                    {% if form.username.errors %}{{form.username.errors}}{% endif %}
                </div>
            </div>
            <div class="mb-3 block ">
                <label class="font-normal" for="id_email">
                    Электронная почта
                </label>
                <input id="id_email" name="email" class="form-field" type="email" 
                {% if form.email.value %} value={{form.email.value}} {% endif %}
                required>
                </input>
                <div class="pt-1 block text-pink-500">
                    {% if form.email.errors %}{{form.email.errors}}{% endif %}
                </div>
            </div>
            <div class="mb-3 block ">
                <label class="font-normal" for="id_hash_algorithm">
                    Метод хеширования мастер пароля
                </label>
                <select name="hash_algorithm" id="id_hash_algorithm" class="form-field">
                    <option value="pbkdf2_sha256" {% if form.initial.settings.preferred_hash_algorithm == "pbkdf2_sha256"%}selected{% endif %}>PBKDF2</option>
                    <option value="argon2" {% if form.initial.settings.preferred_hash_algorithm == "argon2"%}selected{% endif %}>argon2</option>
                </select>
            </div>
            <button type="submit" class="px-2 py-1 w-full border-2 bg-slate-500 border-transparent rounded-md hover:bg-slate-600">
                <span class="font-medium text-white">Сохранить</span>
            </button>
        </form>
        <form action="{% url "users:delete" %}">
            <button type="submit" class="px-2 py-1 w-full border-2 bg-pink-400 border-transparent rounded-md hover:bg-pink-600">
                <span class="font-medium text-white">Удалить пользователя</span>
            </button>
        </form>
        </div>
    </div>

templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% comment %} <script src="{% static "deps/js/registration.js" %}"></script> {% endcomment %}
<div class="fixed w-screen h-screen bg-slate bg-opacity-10">
    <form action="{% url "users:registration" %}" id="registration-form" method="post" class="mx-auto max-w-[1024px] w-full container">
        {% csrf_token %}
        <div class="p-[2rem] mt-5 mx-auto flex flex-col justify-center items-center max-w-[32rem]">
            <div class="p-[1.5rem] bg-white border-gray-200 border-1 rounded-md">
                <div class="font-medium mb-3 text-3xl flex justify-center">
                    {{title}}
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_username">
                        Имя пользователя
                    </label>
                    <input id="id_username" name="username" class="form-field" type="text"
                    {% if form.username.value %} value={{form.username.value}} {% endif %}
                    required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.username.errors %}{{form.username.errors}}{% endif %}
                    </div>
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_email">
                        Электронная почта
                    </label>
                    <input id="id_email" name="email" class="form-field" type="email" 
                    {% if form.email.value %} value={{form.email.value}} {% endif %}
                    required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.email.errors %}{{form.email.errors}}{% endif %}
                    </div>
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_password1">
                        Пароль
                    </label>
                    <input id="id_password1" name="password1" class="form-field" type="password" required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.password1.errors %}{{form.password1.errors}}{% endif %}
                    </div>
                </div>
                <div class="mb-3 block ">
                    <label class="font-normal" for="id_password2">
                        Подтвердите пароль
                    </label>
                    <input id="id_password2" name="password2" class="form-field" type="password" required>
                    </input>
                    <div class="pt-1 block text-pink-500">
                        {% if form.password2.errors %}{{form.password2.errors}}{% endif %}
                    </div>
                    <div class="mb-8 block">
                        <a href="{% url "users:login" %}" class="text-sky-400 hover:text-sky-500 hover:underline">
                            Войти
                        </a>
                    </div>
                </div>
                <button type="submit" class="px-2 py-1 w-full border-2 bg-slate-500 border-transparent rounded-md hover:bg-slate-600">
                    <span class="font-medium text-white">Регистрация</span>
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/users/settings.html
{% extends "base.html" %}
{% load static %}

{% block navigation %}
{% include "includes/navbar.html" %}
{% endblock navigation %}

{% block content %}
{% include "users/profile.html" %}
{% endblock content %}